import {Easing, Interactive, interpolate, useCurrentFrame, useVideoConfig} from "remotion";
import {FilmChrome} from "../components/FilmChrome";

export const ActionScene: React.FC = () => {
  const frame=useCurrentFrame(); const {fps}=useVideoConfig();
  return <FilmChrome step={4} label="Ranked action"><div style={{height:"100%",paddingTop:55}}>
    <Interactive.Div name="Action heading" style={{display:"flex",justifyContent:"space-between",alignItems:"end",opacity:interpolate(frame,[0,.65*fps],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})}}><div><span style={{fontFamily:"Signal Mono",fontSize:16,letterSpacing:"0.12em",color:"#9eb2ff"}}>04 · STRATEGY AGENT</span><h1 style={{margin:"23px 0 0",fontFamily:"Signal Display",fontSize:78,lineHeight:.98,letterSpacing:"-0.05em",fontWeight:500}}>Turn the reason chain into work.</h1></div><p style={{width:480,margin:0,fontSize:23,lineHeight:1.45,color:"#aab5b1"}}>The agent labels observation, inference, and what must be tested next.</p></Interactive.Div>
    <div style={{height:580,marginTop:48,display:"grid",gridTemplateColumns:"1.18fr .82fr",gap:22}}><Interactive.Div name="Strategy answer" style={{padding:34,border:"1px solid #45514c",backgroundColor:"#101816",opacity:interpolate(frame,[.3*fps,1*fps],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.bezier(.16,1,.3,1)})}}><div style={{display:"flex",justifyContent:"space-between",paddingBottom:20,borderBottom:"1px solid #33403b"}}><strong style={{fontFamily:"Signal Display",fontSize:22}}>SIGNAL strategy agent</strong><span style={{fontFamily:"Signal Mono",fontSize:12,color:"#65c4aa"}}>EVIDENCE CONNECTED</span></div><div style={{margin:"30px 0 22px 22%",padding:22,backgroundColor:"#2657ff",fontSize:22}}>What should we do first?</div><div style={{marginRight:"14%",padding:28,border:"1px solid #45514c",backgroundColor:"#151f1c"}}><span style={{fontFamily:"Signal Mono",fontSize:12,color:"#9eb2ff"}}>INFERRED FROM 24 SOURCES</span><h2 style={{margin:"22px 0 16px",fontFamily:"Signal Display",fontSize:40,lineHeight:1.05,letterSpacing:"-0.035em",fontWeight:500}}>Build one proof system the market can verify.</h2><p style={{margin:0,fontSize:18,lineHeight:1.45,color:"#aab5b1"}}>The current strongest proof lives on one owned page. Independent comparisons cannot repeat what they cannot inspect.</p></div></Interactive.Div>
      <Interactive.Div name="Ranked action card" style={{padding:34,border:"1px solid #6687ff",backgroundColor:"#f8faf9",color:"#0b1211",opacity:interpolate(frame,[.75*fps,1.5*fps],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.bezier(.16,1,.3,1)}),translate:interpolate(frame,[.75*fps,1.5*fps],["45px 0px","0px 0px"],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.bezier(.16,1,.3,1)})}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontFamily:"Signal Mono",fontSize:13,color:"#2657ff"}}>PRIORITY 01</span><span style={{padding:"8px 10px",backgroundColor:"#dff0ea",color:"#247a67",fontFamily:"Signal Mono",fontSize:11}}>READY</span></div><h2 style={{margin:"65px 0 22px",fontFamily:"Signal Display",fontSize:46,lineHeight:1.02,letterSpacing:"-0.04em",fontWeight:500}}>Publish one decision-grade comparison.</h2><p style={{fontSize:18,lineHeight:1.45,color:"#55615f"}}>Make the method, limitations, evidence, and buyer fit independently inspectable.</p><div style={{marginTop:42,borderTop:"1px solid #cbd2cf"}}>{[["Owner","Head of marketing"],["Evidence","3 approved proof blocks"],["Rerun","Frozen question set"]].map(([label,value])=><div key={label} style={{minHeight:64,display:"flex",alignItems:"center",justifyContent:"space-between",borderBottom:"1px solid #cbd2cf"}}><span style={{fontFamily:"Signal Mono",fontSize:12,color:"#687370"}}>{label.toUpperCase()}</span><strong style={{fontSize:15}}>{value}</strong></div>)}</div></Interactive.Div></div>
  </div></FilmChrome>;
};
