import {Easing, Interactive, interpolate, useCurrentFrame, useVideoConfig} from "remotion";
import {FilmChrome} from "../components/FilmChrome";

export const EvidenceScene: React.FC = () => {
  const frame=useCurrentFrame(); const {fps}=useVideoConfig();
  return <FilmChrome step={3} label="Source evidence"><div style={{height:"100%",display:"grid",gridTemplateColumns:".72fr 1.28fr",gap:85,alignItems:"center"}}>
    <Interactive.Div name="Evidence summary" style={{opacity:interpolate(frame,[0,.7*fps],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.bezier(.16,1,.3,1)}),translate:interpolate(frame,[0,.7*fps],["0px 45px","0px 0px"],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.bezier(.16,1,.3,1)})}}><span style={{fontFamily:"Signal Mono",fontSize:16,letterSpacing:"0.12em",color:"#9eb2ff"}}>03 · SOURCE EVIDENCE</span><h1 style={{margin:"26px 0",fontFamily:"Signal Display",fontSize:82,lineHeight:.96,letterSpacing:"-0.055em",fontWeight:500}}>Trace the advantage to evidence.</h1><p style={{margin:0,fontSize:25,lineHeight:1.45,color:"#aab5b1"}}>Three independent source types repeat Meridian's implementation proof across the strongest answers.</p><div style={{marginTop:50,paddingTop:24,borderTop:"1px solid #33403b",display:"flex",gap:42}}><div><strong style={{fontFamily:"Signal Display",fontSize:48}}>24</strong><span style={{display:"block",fontFamily:"Signal Mono",fontSize:13,color:"#8b9692"}}>SOURCES OBSERVED</span></div><div><strong style={{fontFamily:"Signal Display",fontSize:48}}>08</strong><span style={{display:"block",fontFamily:"Signal Mono",fontSize:13,color:"#8b9692"}}>REPEAT CITATIONS</span></div></div></Interactive.Div>
    <Interactive.Div name="Evidence map" style={{height:680,position:"relative",padding:42,border:"1px solid #45514c",backgroundColor:"#101816",opacity:interpolate(frame,[.35*fps,1.1*fps],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.bezier(.16,1,.3,1)})}}><div style={{height:72,display:"flex",justifyContent:"space-between",alignItems:"start",borderBottom:"1px solid #33403b"}}><div><span style={{fontFamily:"Signal Mono",fontSize:13,color:"#8b9692"}}>EVIDENCE REASON CHAIN</span><strong style={{display:"block",marginTop:9,fontFamily:"Signal Display",fontSize:26}}>Why Meridian leads the observed set</strong></div><span style={{padding:"9px 12px",border:"1px solid #33403b",fontFamily:"Signal Mono",fontSize:12,color:"#65c4aa"}}>OBSERVED + INFERRED</span></div><div style={{position:"absolute",left:92,right:92,top:270,height:1,backgroundColor:"#3f4b46"}}/>
      {[["01","Independent comparisons","8 repeated citations",100],["02","Implementation reviews","6 proof references",390],["03","Industry profiles","4 entity confirmations",680]].map(([number,title,detail,left],index)=><div key={String(number)} style={{width:260,position:"absolute",left:Number(left),top:210,opacity:interpolate(frame,[(.65+index*.3)*fps,(1.1+index*.3)*fps],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}),translate:interpolate(frame,[(.65+index*.3)*fps,(1.1+index*.3)*fps],["0px 35px","0px 0px"],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.bezier(.16,1,.3,1)})}}><i style={{width:54,height:54,display:"grid",placeItems:"center",position:"relative",zIndex:1,border:"1px solid #6687ff",borderRadius:"50%",backgroundColor:"#101816",color:"#9eb2ff",fontFamily:"Signal Mono",fontSize:13}}>{number}</i><div style={{minHeight:190,marginTop:34,padding:23,border:"1px solid #33403b",backgroundColor:index===1?"#17345e":"#151f1c"}}><span style={{fontFamily:"Signal Mono",fontSize:12,color:"#8b9692"}}>SOURCE TYPE</span><strong style={{display:"block",marginTop:40,fontFamily:"Signal Display",fontSize:25,lineHeight:1.05}}>{title}</strong><small style={{display:"block",marginTop:12,fontSize:15,color:"#aab5b1"}}>{detail}</small></div></div>)}
      <div style={{position:"absolute",left:100,right:100,bottom:44,padding:18,borderLeft:"4px solid #6687ff",backgroundColor:"#1c2b57",fontSize:18,color:"#dfe6ff"}}>Inference: the advantage is repeated, independently verifiable proof, not raw content volume.</div>
    </Interactive.Div>
  </div></FilmChrome>;
};
