import {Easing, Interactive, interpolate, useCurrentFrame, useVideoConfig} from "remotion";
import {FilmChrome} from "../components/FilmChrome";

export const ObservationScene: React.FC = () => {
  const frame=useCurrentFrame(); const {fps}=useVideoConfig();
  return <FilmChrome step={2} label="Observed answer"><div style={{height:"100%",padding:"50px 0 0"}}>
    <Interactive.Div name="Observation heading" style={{display:"flex",justifyContent:"space-between",alignItems:"end",opacity:interpolate(frame,[0,.7*fps],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.bezier(.16,1,.3,1)})}}><div><span style={{fontFamily:"Signal Mono",fontSize:16,letterSpacing:"0.12em",color:"#9eb2ff"}}>02 · OBSERVED ANSWER</span><h1 style={{margin:"24px 0 0",fontFamily:"Signal Display",fontSize:76,lineHeight:.98,letterSpacing:"-0.05em",fontWeight:500}}>See who appears. Keep inference out.</h1></div><p style={{width:470,margin:0,fontSize:23,lineHeight:1.45,color:"#aab5b1"}}>48 synthetic responses captured across a fixed six-engine sample.</p></Interactive.Div>
    <Interactive.Div name="Observed answer dashboard" style={{height:575,marginTop:50,display:"grid",gridTemplateColumns:"1.25fr .75fr",border:"1px solid #45514c",backgroundColor:"#f8faf9",color:"#0b1211",boxShadow:"0 35px 90px rgba(0,0,0,.3)",opacity:interpolate(frame,[.35*fps,1.2*fps],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.bezier(.16,1,.3,1)}),translate:interpolate(frame,[.35*fps,1.2*fps],["0px 45px","0px 0px"],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.bezier(.16,1,.3,1)})}}>
      <div style={{padding:32,borderRight:"1px solid #cbd2cf"}}><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",borderTop:"1px solid #0b1211"}}>{[["Answer coverage","37%"],["Leading competitor","62%"],["Priority gaps","03"]].map(([label,value])=><div key={label} style={{minHeight:125,padding:20,borderRight:"1px solid #cbd2cf",borderBottom:"1px solid #cbd2cf"}}><span style={{fontFamily:"Signal Mono",fontSize:13,color:"#687370"}}>{label.toUpperCase()}</span><strong style={{display:"block",marginTop:24,fontFamily:"Signal Display",fontSize:48,letterSpacing:"-0.04em"}}>{value}</strong></div>)}</div><div style={{height:330,marginTop:28,padding:24,border:"1px solid #cbd2cf"}}><span style={{fontFamily:"Signal Mono",fontSize:13,color:"#687370"}}>ANSWER COVERAGE · FROZEN SAMPLE</span><div style={{height:245,display:"flex",alignItems:"end",gap:18,paddingTop:24}}>{[31,35,33,36,37,39,37,37].map((value,index)=><div key={index} style={{height:"100%",flex:1,display:"flex",alignItems:"end"}}><i style={{width:"100%",height:`${value*2.1}px`,display:"block",backgroundColor:index===7?"#2657ff":"#d7ddda",scale:interpolate(frame,[.8*fps,(1.1+index*.08)*fps],["1 0","1 1"],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.spring({damping:200})}),transformOrigin:"bottom"}}/></div>)}</div></div></div>
      <div style={{padding:32}}><span style={{fontFamily:"Signal Mono",fontSize:13,color:"#687370"}}>ENGINE OBSERVATIONS</span><div style={{marginTop:25}}>{[["ChatGPT","Meridian",true],["Google AI","Meridian",true],["Gemini","Meridian",true],["Perplexity","Sample Co.",false],["Claude","Meridian",true],["Copilot","Sample Co.",false]].map(([engine,brand,lead],index)=><div key={String(engine)} style={{minHeight:74,display:"grid",gridTemplateColumns:"1fr 1fr auto",alignItems:"center",borderTop:"1px solid #cbd2cf",opacity:interpolate(frame,[(.8+index*.13)*fps,(1.15+index*.13)*fps],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})}}><strong style={{fontSize:18}}>{engine}</strong><span style={{fontSize:16,color:"#55615f"}}>{brand}</span><i style={{width:10,height:10,borderRadius:"50%",backgroundColor:lead?"#2657ff":"#247a67"}}/></div>)}</div><p style={{margin:"26px 0 0",padding:18,backgroundColor:"#e7ecff",fontSize:16,lineHeight:1.35}}>Observation: Meridian appears in 30 of 48 answers. The cause has not yet been assigned.</p></div>
    </Interactive.Div>
  </div></FilmChrome>;
};
