create table public.ai_visibility_leads (
  id uuid primary key default gen_random_uuid(),
  request_type text not null check (request_type in ('free_audit', 'guide_download', 'strategy_call')),
  full_name text not null check (char_length(btrim(full_name)) between 1 and 120),
  email_normalized text not null check (
    email_normalized = lower(btrim(email_normalized))
    and char_length(email_normalized) between 3 and 320
  ),
  company_name text not null check (char_length(btrim(company_name)) between 1 and 160),
  website_url text not null check (website_url ~ '^https?://[^[:space:]]+$' and char_length(website_url) <= 2048),
  annual_revenue_range text not null check (annual_revenue_range in ('pre_revenue', 'under_250k', '250k_1m', '1m_5m', '5m_20m', '20m_plus', 'prefer_not_to_say')),
  role_title text check (role_title is null or char_length(btrim(role_title)) between 1 and 120),
  ai_goal text check (ai_goal is null or char_length(btrim(ai_goal)) between 1 and 1500),
  timing text check (timing is null or timing in ('now', '30-60-days', 'later', 'exploring')),
  source_context jsonb not null default '{}'::jsonb check (jsonb_typeof(source_context) = 'object'),
  status text not null default 'new' check (status in ('new', 'contacted', 'qualified', 'booked', 'proposal', 'won', 'lost', 'spam')),
  owner_user_id uuid references auth.users (id) on delete set null,
  next_action_at timestamptz,
  consent_version text not null check (char_length(btrim(consent_version)) between 1 and 64),
  consented_at timestamptz not null default now(),
  first_submitted_at timestamptz not null default now(),
  last_submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ai_visibility_lead_events (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references public.ai_visibility_leads (id) on delete cascade,
  event_type text not null check (char_length(btrim(event_type)) between 1 and 80),
  event_key text unique check (event_key is null or char_length(event_key) between 1 and 300),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  actor_user_id uuid default auth.uid() references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.ai_visibility_booking_events (
  id bigint generated by default as identity primary key,
  email_normalized text not null check (
    email_normalized = lower(btrim(email_normalized))
    and char_length(email_normalized) between 3 and 320
  ),
  event_type text not null check (char_length(btrim(event_type)) between 1 and 120),
  event_key text not null unique check (char_length(event_key) between 1 and 300),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  matched_lead_id uuid references public.ai_visibility_leads (id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.lead_capture_rate_limits (
  fingerprint text primary key check (char_length(fingerprint) = 64),
  window_started_at timestamptz not null default now(),
  attempt_count smallint not null default 1 check (attempt_count between 1 and 100),
  updated_at timestamptz not null default now()
);

create unique index ai_visibility_leads_identity_idx
on public.ai_visibility_leads (email_normalized, website_url);

create index ai_visibility_leads_status_next_action_idx
on public.ai_visibility_leads (status, next_action_at nulls first, created_at desc);

create index ai_visibility_lead_events_timeline_idx
on public.ai_visibility_lead_events (lead_id, created_at desc);

create index ai_visibility_booking_events_email_idx
on public.ai_visibility_booking_events (email_normalized, created_at desc);

create trigger ai_visibility_leads_set_updated_at
before update on public.ai_visibility_leads
for each row execute function public.set_updated_at();

create trigger lead_capture_rate_limits_set_updated_at
before update on public.lead_capture_rate_limits
for each row execute function public.set_updated_at();

alter table public.ai_visibility_leads enable row level security;
alter table public.ai_visibility_leads force row level security;
alter table public.ai_visibility_lead_events enable row level security;
alter table public.ai_visibility_lead_events force row level security;
alter table public.ai_visibility_booking_events enable row level security;
alter table public.ai_visibility_booking_events force row level security;
alter table public.lead_capture_rate_limits enable row level security;
alter table public.lead_capture_rate_limits force row level security;

create policy ai_visibility_leads_admin_select
on public.ai_visibility_leads
for select
to authenticated
using ((select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'));

create policy ai_visibility_leads_admin_update
on public.ai_visibility_leads
for update
to authenticated
using ((select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'))
with check ((select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'));

create policy ai_visibility_lead_events_admin_select
on public.ai_visibility_lead_events
for select
to authenticated
using ((select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'));

create policy ai_visibility_lead_events_admin_insert
on public.ai_visibility_lead_events
for insert
to authenticated
with check ((select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'));

create policy ai_visibility_booking_events_admin_select
on public.ai_visibility_booking_events
for select
to authenticated
using ((select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'));

revoke all on table public.ai_visibility_leads from public, anon, authenticated;
revoke all on table public.ai_visibility_lead_events from public, anon, authenticated;
revoke all on table public.ai_visibility_booking_events from public, anon, authenticated;
revoke all on table public.lead_capture_rate_limits from public, anon, authenticated;

grant select, update on table public.ai_visibility_leads to authenticated;
grant select, insert on table public.ai_visibility_lead_events to authenticated;
grant select on table public.ai_visibility_booking_events to authenticated;
grant usage, select on sequence public.ai_visibility_lead_events_id_seq to authenticated;
grant usage, select on sequence public.ai_visibility_booking_events_id_seq to authenticated;

grant select, insert, update, delete on table public.ai_visibility_leads to service_role;
grant select, insert, update, delete on table public.ai_visibility_lead_events to service_role;
grant select, insert, update, delete on table public.ai_visibility_booking_events to service_role;
grant usage, select on sequence public.ai_visibility_lead_events_id_seq to service_role;
grant usage, select on sequence public.ai_visibility_booking_events_id_seq to service_role;
grant select, insert, update, delete on table public.lead_capture_rate_limits to service_role;

create function public.capture_ai_visibility_lead(
  p_submission_id uuid,
  p_fingerprint text,
  p_request_type text,
  p_name text,
  p_email_normalized text,
  p_company_name text,
  p_website_url text,
  p_role_title text,
  p_ai_goal text,
  p_timing text,
  p_annual_revenue_range text,
  p_source_context jsonb,
  p_consent_version text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_limit public.lead_capture_rate_limits%rowtype;
  v_lead public.ai_visibility_leads%rowtype;
  v_created boolean := false;
begin
  if p_submission_id is null
    or p_fingerprint !~ '^[0-9a-f]{64}$'
    or p_request_type not in ('free_audit', 'guide_download', 'strategy_call')
    or char_length(btrim(coalesce(p_name, ''))) not between 1 and 120
    or char_length(lower(btrim(coalesce(p_email_normalized, '')))) not between 3 and 320
    or char_length(btrim(coalesce(p_company_name, ''))) not between 1 and 160
    or p_annual_revenue_range not in ('pre_revenue', 'under_250k', '250k_1m', '1m_5m', '5m_20m', '20m_plus', 'prefer_not_to_say')
    or (p_role_title is not null and char_length(btrim(p_role_title)) not between 1 and 120)
    or (p_ai_goal is not null and char_length(btrim(p_ai_goal)) not between 1 and 1500)
    or (p_timing is not null and p_timing not in ('now', '30-60-days', 'later', 'exploring'))
    or (p_request_type = 'free_audit' and (
      char_length(btrim(coalesce(p_role_title, ''))) not between 1 and 120
      or char_length(btrim(coalesce(p_ai_goal, ''))) not between 1 and 1500
      or p_timing not in ('now', '30-60-days', 'later', 'exploring')
    ))
    or jsonb_typeof(coalesce(p_source_context, '{}'::jsonb)) <> 'object' then
    return jsonb_build_object('reason', 'invalid_claim');
  end if;

  insert into public.lead_capture_rate_limits as limits (fingerprint, window_started_at, attempt_count)
  values (p_fingerprint, now(), 1)
  on conflict (fingerprint) do update
  set
    window_started_at = case when limits.window_started_at < now() - interval '1 hour' then now() else limits.window_started_at end,
    attempt_count = case when limits.window_started_at < now() - interval '1 hour' then 1 else limits.attempt_count + 1 end
  returning * into v_limit;

  if v_limit.attempt_count > 5 then
    return jsonb_build_object('reason', 'rate_limited');
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(lower(btrim(p_email_normalized)) || '|' || p_website_url, 0)
  );

  select leads.*
  into v_lead
  from public.ai_visibility_leads as leads
  where leads.email_normalized = lower(btrim(p_email_normalized))
    and leads.website_url = p_website_url
  order by leads.last_submitted_at desc
  limit 1
  for update;

  if found then
    update public.ai_visibility_leads
    set
      request_type = p_request_type,
      full_name = btrim(p_name),
      company_name = btrim(p_company_name),
      annual_revenue_range = p_annual_revenue_range,
      role_title = nullif(btrim(coalesce(p_role_title, '')), ''),
      ai_goal = nullif(btrim(coalesce(p_ai_goal, '')), ''),
      timing = p_timing,
      source_context = coalesce(p_source_context, '{}'::jsonb),
      consent_version = btrim(p_consent_version),
      consented_at = now(),
      last_submitted_at = now()
    where id = v_lead.id
    returning * into v_lead;
  else
    insert into public.ai_visibility_leads (
      request_type,
      full_name,
      email_normalized,
      company_name,
      website_url,
      annual_revenue_range,
      role_title,
      ai_goal,
      timing,
      source_context,
      consent_version
    ) values (
      p_request_type,
      btrim(p_name),
      lower(btrim(p_email_normalized)),
      btrim(p_company_name),
      p_website_url,
      p_annual_revenue_range,
      nullif(btrim(coalesce(p_role_title, '')), ''),
      nullif(btrim(coalesce(p_ai_goal, '')), ''),
      p_timing,
      coalesce(p_source_context, '{}'::jsonb),
      btrim(p_consent_version)
    )
    returning * into v_lead;
    v_created := true;
  end if;

  insert into public.ai_visibility_lead_events (lead_id, event_type, event_key, payload)
  values (
    v_lead.id,
    'submission',
    'submission:' || p_submission_id::text,
    jsonb_build_object('source', coalesce(p_source_context, '{}'::jsonb), 'requestType', p_request_type, 'annualRevenueRange', p_annual_revenue_range, 'deduplicated', not v_created)
  )
  on conflict (event_key) do nothing;

  return jsonb_build_object('reason', case when v_created then 'created' else 'deduplicated' end, 'lead_id', v_lead.id, 'created', v_created);
end;
$$;

revoke all on function public.capture_ai_visibility_lead(uuid, text, text, text, text, text, text, text, text, text, text, jsonb, text)
from public, anon, authenticated;
grant execute on function public.capture_ai_visibility_lead(uuid, text, text, text, text, text, text, text, text, text, text, jsonb, text)
to service_role;

create function public.record_ai_visibility_booking(
  p_email_normalized text,
  p_event_type text,
  p_event_key text,
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_lead public.ai_visibility_leads%rowtype;
  v_event text := lower(btrim(coalesce(p_event_type, 'booking_event')));
begin
  select leads.*
  into v_lead
  from public.ai_visibility_leads as leads
  where leads.email_normalized = lower(btrim(p_email_normalized))
    and leads.last_submitted_at >= now() - interval '180 days'
  order by leads.last_submitted_at desc
  limit 1
  for update;

  if not found then
    insert into public.ai_visibility_booking_events (email_normalized, event_type, event_key, payload)
    values (lower(btrim(p_email_normalized)), left(v_event, 120), left(p_event_key, 300), coalesce(p_payload, '{}'::jsonb))
    on conflict (event_key) do nothing;
    return jsonb_build_object('matched', false);
  end if;

  insert into public.ai_visibility_booking_events (email_normalized, event_type, event_key, payload, matched_lead_id)
  values (lower(btrim(p_email_normalized)), left(v_event, 120), left(p_event_key, 300), coalesce(p_payload, '{}'::jsonb), v_lead.id)
  on conflict (event_key) do update set matched_lead_id = excluded.matched_lead_id;

  insert into public.ai_visibility_lead_events (lead_id, event_type, event_key, payload)
  values (v_lead.id, left(v_event, 80), left(p_event_key, 300), coalesce(p_payload, '{}'::jsonb))
  on conflict (event_key) do nothing;

  if v_event like '%cancel%' and v_lead.status = 'booked' then
    update public.ai_visibility_leads set status = 'qualified', next_action_at = now() where id = v_lead.id;
  elsif (v_event like '%created%' or v_event like '%rescheduled%' or v_event like '%booking%')
    and v_lead.status in ('new', 'contacted', 'qualified') then
    update public.ai_visibility_leads set status = 'booked', next_action_at = null where id = v_lead.id;
  end if;

  return jsonb_build_object('matched', true, 'lead_id', v_lead.id);
end;
$$;

revoke all on function public.record_ai_visibility_booking(text, text, text, jsonb)
from public, anon, authenticated;
grant execute on function public.record_ai_visibility_booking(text, text, text, jsonb)
to service_role;

create function public.log_ai_visibility_lead_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.status is distinct from new.status
    or old.owner_user_id is distinct from new.owner_user_id
    or old.next_action_at is distinct from new.next_action_at then
    insert into public.ai_visibility_lead_events (lead_id, event_type, payload, actor_user_id)
    values (
      new.id,
      'lead_updated',
      jsonb_build_object(
        'statusFrom', old.status,
        'statusTo', new.status,
        'ownerChanged', old.owner_user_id is distinct from new.owner_user_id,
        'nextActionAt', new.next_action_at
      ),
      auth.uid()
    );
  end if;
  return new;
end;
$$;

create trigger ai_visibility_lead_change_event
after update on public.ai_visibility_leads
for each row execute function public.log_ai_visibility_lead_change();

revoke all on function public.log_ai_visibility_lead_change()
from public, anon, authenticated;
